server:
  ipAddr: 520.02.shiina.shino
  name01: "\u96EA\u4E43"
  name02: "\u6A58\u6885"

cfserver:
  timeout: 30
  dataSize: 40
#  time01: 10
#  memory01: 20



logging:
  logback:
    rollingpolicy:
      max-file-size: 500B
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
